[dart] Roll dart to b99bcfd3099f0d32e39287160a9539e878cb0b68 (#6491)
* [dart] Roll dart to b99bcfd3099f0d32e39287160a9539e878cb0b68

Changes since last roll:
```
b99bcfd309 [vm] Add a library and class cache to KernelProgramInfo
5deb1c6e81 [vm] Remove strong mode and sync-async flags from pkg/vm
9a6f811466 Report null error as a NoSuchMethodError
2da0b9f4f1 fix some typos
34f6aea008 [release] Prepare changelog for 2.1.0-dev.7.0
f320477ff9 [dartdevc] add module-name option to kernel backend
b8760fed67 [vm, compiler] Remove ASTs and AST flow graph builder.
340e74629f Clean up OverrideVerifier.
f11e746c2e Initial implementation of fixes for type arguments on named constructor invocations
08e485c43f Update dartdoc to 0.23.1.
ac4b8a7306 Hook up FixProcessor to fix errors in dartfix
0aa99cca99 Ignore JSON exceptions when reading (empty) test results file
6d9cc6fa03 Add skeleton for parsing LSP spec from Markdown/TypeScript to generate Dart data classes
bc4d2f5d1b Switch InheritanceManager2Test to DriverResolutionTest.
e221a6288b Move reporting MISMATCHED_GETTER_AND_SETTER_TYPES for classes to using new interfaces.
be39eacf00 Rename convertPathForImport -> convertAbsolutePathToUri
a539d2ef5f Revert "[fasta] Report errors for bounds violations"
c8b709d95b Update status files after aa6fb2d3
051108c004 [tools] Re-enable core-dump archiving on Linux.
aa5b1b1f2f Make test results in json format end with a newline
4db2bbe94d Pass SharedOptions to Fasta
f1d902f4a0 Ignore --supermixin and -D options
a9b47bd0b1 Integrated nosuchmethod-forwarding.md into dartLangSpec.tex
327a1a9a00 [Gardening] Mark more co19_2 test as always flaky, filed co19 issues
f1b6d81404 Remove Target.strongMode
7072d3b17e [infra] Upgrade d8 to 6.9.427.23 (#34698)
16ddfc1565 [VM] Use assert assignable implementation for explicit downcasts
17ac151f44 [Gardening] Increase timeout on release-hotreload configuration as well (not just debug), skip streamed_conversion_json_utf8_decode in hot-reload-simdbc64
8c872e0e3a Remove TargetFlags.strongMode
ee97806084 Replace strongMode with legacyMode in CompilerOptions
aa6fb2d3a4 [fasta] Report errors for bounds violations
8247fb7eec Stop stripping d8 for benchmarking.
da48c1d960 [Gardening] Mark more tests as flaky and filed co19 issues
41866e87da [Gardening] Mark co19_2 test as always flaky, filed co19 issue (and co19 PR)
ecd13de9da [Gardening] Mark slow_path_shared_stub_test as slow (reaches 1 minute on windows)
f942af451b Remove kernel interpreter
7007567685 Fix issue with --unsafe-package-serialization
2695f36016 [Gardening] Status update (co19_2, optcounter/ia32)
ba5e14b195 Store return type and parameters separately in GenericFunctionTypeElementForLink.
ba1b30af37 Add AST support for type arguments on named constructors
ed6c557d1a Add cli parameters to kernel_sdk.dart to get all paths explicitly
71395df7dd [vm/interpreter] Fix flaky errors when running with interpreter
b3af151325 Rework detection of uninstantiated bound errors.
34651d204e [gardening] Update status
f35465dafd Remove DynamicElementImpl.library property.
daa13ad0aa Fix preamble/d8.js currentScript for v8 6.9
9cde31ba1d Try interface candidates in reverse order.
5561e69f4e Replace dartfix confirm apply changes with --force
619a06370e Update dartfix to only allow target directories
751cf1974a [dart/fuzzer] Add DBC as execution mode.
70317473f0 [gardening] Update status
8fc80031ae Fix cast exception in OpTypeAstVisitor
2cf6ba2996 Generate the right error message for type arguments on a named constructor
5976fe373f Fix up InferredTypeTest_Driver to use InferredTypeMixin directly.
32c484bb71 [VM] Fix typo in BitTestImmediate unit test.
a8e0db1077 [gardening] Mark remaining ASAN failures.
7f55e52888 [vm, x64] Use short forms for object pool loads.
a66cae48fc [vm/aot] Dynamic invocation forwarders in AOT.
4400df4190 Convert strong_mode_test.dart to triple-slash comment style.
c1361963aa Update status files for tests failing due to #34724 and #34724
0039aff1e3 [test] Remove use of --error_on_bad_type and --error_on_bad_override.
ce08911515 [vm/compiler] Minor improvements to loop detection
a2cf88bee6 [vm] Fix sync-async stack navigation to handle inlined functions.
920d75f2ea Cleanup dartfix driver context
746034785d Update dartfix to separate targets from analysis roots
3d06427075 Fix MOVE_FILE test paths for Windows
```

* Remove use of await_is_keyword flag.

* Update license